//Caroline Barrineau, Team Victor
public enum Amenities {
	
	SHUTTLE, 
	PETS,
	FURNISHED,
	GYM,
	POOL,
	WASHER_DRYER_CONNECTIONS,
	WASHER_DRYER_INCLUDED,
	ONSITE_LAUNDRY,
	GARBAGE_PICKUP,
	STREET_PARKING,
	GARAGE_PARKING,
	DRIVEWAY,
	FREE_WIFI;
}
